# Generated by Django 5.1.4 on 2024-12-12 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_diagnosis_description_alter_diagnosis_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Heal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(choices=[('flu_treatment', 'Лечение гриппа: отдых, питье, жаропонижающие.'), ('pneumonia_treatment', 'Лечение пневмонии: антибиотики, госпитализация.'), ('allergy_treatment', 'Лечение аллергии: антигистамины, избегание аллергена.'), ('cold_treatment', 'Лечение простуды: теплые напитки, отдых, витамины.')], default='flu_treatment', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ManyToManyField(blank=True, related_name='customuser_set', to='hospital.diagnosis')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
